version: "3.7"

services:

  # Website
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    depends_on:
     - db
     - cms
    ports:
     - "3000:3000"
    environment:
      WAIT_HOSTS: cms:1337 # Wait for the CMS to start before launching frontend

  # Content management system
  cms:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      DATABASE_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./STRAPI_APP_CONTENT:/srv/app
    depends_on:
      - db
    ports:
      - "1337:1337"


  # Database
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/data/db

volumes:
  # Database persistence
  db-data:
